[project]
name = "sticky"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["mypy>=1.19.1"]

[tool.mypy]
pretty = true
strict = true
disallow_any_expr = true
disallow_any_explicit = true
warn_unreachable = true
exclude_gitignore = true
